# Generated by Django 5.2.17 on 2026-09-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verifyed',
            field=models.BooleanField(default=False),
        ),
    ]
