# Generated by Django 5.2.17 on 2026-09-22 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowabooks',
            name='client_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowabooks',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_books', to='users.employee'),
        ),
        migrations.AddField(
            model_name='borrowabook',
            name='borrow_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_book', to='app.borrowabooks'),
        ),
        migrations.AddField(
            model_name='categorychillzones',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_chill_zones', to='app.categories'),
        ),
        migrations.AddField(
            model_name='chillzonebookings',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chill_zone_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chillzonebookings',
            name='chill_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.chillzones'),
        ),
        migrations.AddField(
            model_name='categorychillzones',
            name='chill_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_chill_zones', to='app.chillzones'),
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='app.genres'),
        ),
        migrations.AddField(
            model_name='libraries',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cities'),
        ),
        migrations.AddField(
            model_name='chillzones',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chill_zones', to='app.libraries'),
        ),
        migrations.AddField(
            model_name='borrowabooks',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.libraries'),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='app.books'),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='app.libraries'),
        ),
        migrations.AddField(
            model_name='libraries',
            name='book',
            field=models.ManyToManyField(related_name='libraries', through='app.LibraryBook', to='app.books'),
        ),
        migrations.AddField(
            model_name='orders',
            name='chill_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chillzones'),
        ),
        migrations.AddField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.employee'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.payments'),
        ),
        migrations.AddField(
            model_name='borrowabooks',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.payments'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paymenttypes'),
        ),
        migrations.AddField(
            model_name='libraries',
            name='payment_type',
            field=models.ManyToManyField(related_name='payment_type', to='app.paymenttypes'),
        ),
        migrations.AddField(
            model_name='chillzones',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paymenttypes'),
        ),
        migrations.AddField(
            model_name='positions',
            name='default_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='productorders',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productorders',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='The employee who processed the purchase at the checkout (optional—the customer can make the purchase themselves).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to='users.employee'),
        ),
        migrations.AddField(
            model_name='productorders',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='app.payments'),
        ),
        migrations.AddField(
            model_name='productorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.productorders'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(related_name='category', to='app.categories'),
        ),
        migrations.AddField(
            model_name='productorderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products'),
        ),
        migrations.AddField(
            model_name='receiptproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products'),
        ),
        migrations.AddField(
            model_name='receipts',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='app.orders'),
        ),
        migrations.AddField(
            model_name='receiptproducts',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receipts'),
        ),
        migrations.AddField(
            model_name='libraries',
            name='shift',
            field=models.ManyToManyField(related_name='shift', to='app.shifts'),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ManyToManyField(related_name='suppliers', to='app.suppliers'),
        ),
        migrations.AlterUniqueTogether(
            name='categorychillzones',
            unique_together={('category', 'chill_zone')},
        ),
        migrations.AlterUniqueTogether(
            name='librarybook',
            unique_together={('library', 'book')},
        ),
    ]
