# Generated by Django 5.2.17 on 2026-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='book', to='app.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='book', to='app.genres'),
        ),
    ]
