# Generated by Django 6.1.1 on 2026-09-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orders_employee_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorders',
            name='client',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='productorders',
            name='payment',
        ),
        migrations.DeleteModel(
            name='ProductOrderItems',
        ),
        migrations.DeleteModel(
            name='ProductOrders',
        ),
    ]
